apiVersion: v1
kind: Namespace
metadata:
  name: comd

---

apiVersion: v1
kind: Service
metadata:
  name: keycloak
  namespace: comd
  labels:
    name: keycloak
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    nodePort: 30080  
  selector:
    name: keycloak
  type: NodePort
  
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-db
  namespace: comd
spec:
  type: NodePort
  ports:
  - name: mongoport
    port: 27017
    targetPort: 27017
    nodePort: 30017
  selector:
    app: mongo-db
    
---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: keycloak
  namespace: comd
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: keycloak
    spec:  
      hostname: keycloak   
      containers:
      - name: keycloak
        image: jboss/keycloak
        env:
        - name: POSTGRES_DB
          value: keycloak
        - name: DB_USER
          value: keycloak
        - name: DB_PASSWORD
          value: password
        - name: KEYCLOAK_USER
          value: admin
        - name: KEYCLOAK_PASSWORD
          value: Pa55w0rd
        ports:
          - name: http
            containerPort: 8080
      volumes:
        - name: keycloakdata
          hostPath:
            path: /root/keycloakdata

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: postgres
  namespace: comd
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: postgres
    spec:    
      hostname: postgres   
      containers:
      - name: postgres
        image: postgres
        env:
        - name: POSTGRES_DB
          value: keycloak
        - name: POSTGRES_USER
          value: keycloak
        - name: POSTGRES_PASSWORD
          value: password
        volumeMounts:
          - mountPath: /var/lib/postgresql/data
            name: postgresdata        
      volumes:
        - name: postgresdata
          hostPath:
            path: /root/postgresdata
---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mongo-deployment
  namespace: comd
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: mongo-db
    spec:   
      hostname: mongo-db    
      containers:
      - name: mongo-db.comd
        image: mongo:latest                  
        volumeMounts:
          - mountPath: /data/db
            name: mongodbdata  
          - mountPath: /data/configdb
            name: mongodbconfig 
        ports:
          - containerPort: 27017
      volumes:
        - name: mongodbdata
          hostPath:
            path: /root/db
        - name: mongodbconfig
          hostPath:
            path: /root/configdb
      
            
            